[tool.ruff]
line-length = 120
fix = true
lint.select = ["ALL"]
lint.ignore = ["D1", "D203", "D213", "FA102", "ANN204", "S113", "B904", "F821", "RUF012"]
cache-dir = "/tmp/ruff-cache/"
extend-exclude = ["tests", "src/bad.py"]


[tool.ruff.lint.isort]
lines-after-imports = 2
no-lines-before = ["standard-library", "local-folder"]
known-third-party = []
known-local-folder = ["source"]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
docstring-code-format = true
